version: 2
updates:

  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
