# This is a sample configuration for the Pulsar Heartbeat
# For all configuration options, see ./src/cfg/config.go
---
name: # Pulsar cluster name, required
tokenFilePath: # path to pulsar jwt, takes precedence over token, if both present
token: # pulsar jwt
trustStore: # path to tls truststore
prometheusConfig:
  port: ":8080"
  exposeMetrics: true
slackConfig:
  alertUrl: # required for slack integration to work
sitesConfig:
  sites:
opsGenieConfig:
  intervalSeconds: 180
  heartbeatKey: GenieKey key for heartbeat
  alertKey: GenieKey api key to generate alerts or incidents
pulsarAdminRestConfig:
  intervalSeconds: 120
  Token: # pulsar jwt, required for pulsarAdminRestConfig to work
  clusters:
  - name: cluster1-azure
    url: https://cluster1.azure.kafkaesque.io:8964/
    alertPolicy:
      Ceiling: 10
      MovingWindowSeconds: 30
      CeilingInMovingWindow: 10
pulsarTopicConfig:
  - latencyBudgetMs: 360
    intervalSeconds: 60
    pulsarUrl: pulsar+ssl://cluster3.gcp.kafkaesque.io:6651
    topicName: persistent://tenant/ns2/reserved-cluster-monitoring
    payloadSizes: [ 15B ]
    numberOfMessages: 1
    alertPolicy:
      Ceiling: 30
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5
analyticsConfig:
  apiKey:
  ingestionURL:
  insightsWriteKey:
  insightsAccountId: ""
k8sConfig:
  enabled: false
  pulsarNamespace: default
brokersConfig:
  intervalSeconds: 45
  inclusterRestURL: "http://pulsar-broker:8080"
  alertPolicy:
    Ceiling: 5
    MovingWindowSeconds: 600
    CeilingInMovingWindow: 8
webSocketConfig:
  - latencyBudgetMs: 640
    name: websocket_cluster3_gcp
    intervalSeconds: 60
    cluster: cluster3.gcp.kafkaesque.io
    topicName: persistent/tenant/ns2/test-topic234
    scheme: "wss://"
    port: "8500"
    urlQueryParams: "token="
  - latencyBudgetMs: 640
    name: websocket_cluster1_azure
    intervalSeconds: 65
    cluster: cluster1.azure.kafkaesque.io
    topicName: persistent/tenant/ns2/test-topic234
    scheme: "wss://"
    port: "8500"
    urlQueryParams: "token="
  - latencyBudgetMs: 640
    name: websocket_cluster2_aws
    intervalSeconds: 55
    cluster: cluster2.aws.kafkaesque.io
    topicName: persistent/tenant/ns2/test-topic234
    scheme: "wss://"
    port: "8500"
    urlQueryParams: "token="
