---
prometheusConfig:
  port: ":8080"
  exposeMetrics: true
slackConfig:
  alertUrl: required
sitesConfig:
  sites:
opsGenieConfig:
  intervalSeconds: 180
  heartbeatKey: GenieKey key for heartbeat
  alertKey: GenieKey api key to generate alerts or incidents
pulsarOpsConfig:
  intervalSeconds: 120
  masterToken: pulsar jwt required
  clusters:
  - name: cluster1-azure
    url: https://cluster1.azure.kafkaesque.io:8964/
    alertPolicy:
      Ceiling: 10
      MovingWindowSeconds: 30
      CeilingInMovingWindow: 10
  - name: cluster2-aws
    url: https://cluster2.aws.kafkaesque.io:8964/
    alertPolicy:
      Ceiling: 10
      MovingWindowSeconds: 30
      CeilingInMovingWindow: 10
  - name: cluster3-gcp
    url: https://cluster3.gcp.kafkaesque.io:8964/
    alertPolicy:
      Ceiling: 10
      MovingWindowSeconds: 30
      CeilingInMovingWindow: 10
pulsarPerfConfig:
  intervalSeconds: 120
  token: ''
  topicCfgs:
  - latencyBudgetMs: 360
    pulsarUrl: pulsar+ssl://cluster3.gcp.kafkaesque.io:6651
    topicName: persistent://tenant/ns2/reserved-cluster-monitoring
    alertPolicy:
      Ceiling: 30
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5
  - latencyBudgetMs: 2400
    pulsarUrl: pulsar+ssl://cluster2.aws.kafkaesque.io:6651
    topicName: persistent://tenant/ns/reserved-cluster-monitoring
    payloadSizes: ["200B"]
    numberOfMessages: 1
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5
  - latencyBudgetMs: 1850
    pulsarUrl: pulsar+ssl://cluster1.azure.kafkaesque.io:6651
    topicName: persistent://tenant/ns/reserved-cluster-monitoring
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5

websocketConfig:
  - latencyBudgetMs: 640
    name: websocket_cluster3_gcp
    intervalSeconds: 60
    cluster: cluster3.gcp.kafkaesque.io
    topicName: persistent/tenant/ns2/test-topic234
    scheme: "wss://"
    port: "8500"
    urlQueryParams: "token="
  - latencyBudgetMs: 640
    name: websocket_cluster1_azure
    intervalSeconds: 65
    cluster: cluster1.azure.kafkaesque.io
    topicName: persistent/tenant/ns2/test-topic234
    scheme: "wss://"
    port: "8500"
    urlQueryParams: "token="
  - latencyBudgetMs: 640
    name: websocket_cluster2_aws
    intervalSeconds: 55
    cluster: cluster2.aws.kafkaesque.io
    topicName: persistent/tenant/ns2/test-topic234
    scheme: "wss://"
    port: "8500"
    urlQueryParams: "token="
